{
  "name": "les-ptits-trinquat-web",
  "type": "javascript",
  "main": "dist/index.html",
  "build": {
    "command": "npm run build",
    "cwd": "."
  },
  "env": {
    "production": {
      "name": "les-ptits-trinquat-web-prod"
    }
  },
  "routes": [
    {
      "pattern": "^/.*$",
      "custom_domain": true
    }
  ]
}
