name = "les-ptits-trinquat-web"
type = "javascript"
main = "dist/index.html"
compatibility_date = "2024-12-13"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "les-ptits-trinquat-web-prod"

[[routes]]
pattern = "^/.*$"
custom_domain = true

[build.upload]
format = "service-worker"
